### ISSUE TITLE
Secret key for message not found.

### ISSUE THREAD

**Issue by kntjspr** [dhaven/ProtonDriveSync#4]
Extended log:
```
Unable to initialize user keys: Secret key for message not found.
ProtonDriveSync
   at ProtonDriveSync.StorageProvider.ProtonAPI.<InitUserKeys>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.StorageProvider.ProtonDriveStorageProvider.<Init>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.ProtonDriveSyncExt.<OnShowSetting>d__8.MoveNext()
Void MoveNext()
```

**Comment by devilski** [comment]
Having the same issue as well

**Comment by migueldans** [comment]
**Same issue**

Keepass 2.56
ProtonDriveSync 0.1.3

image:
![image](https://github.com/dhaven/ProtonDriveSync/assets/39558093/3e4eec07-150e-4f13-bb8c-5b877855fdf1)

log:

Unable to initialize user keys: Secret key for message not found.
ProtonDriveSync
   at ProtonDriveSync.StorageProvider.ProtonAPI.<InitUserKeys>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.StorageProvider.ProtonDriveStorageProvider.<Init>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.ProtonDriveSyncExt.<OnShowSetting>d__8.MoveNext()
Void MoveNext()
